### ISSUE TITLE
"CL.exe" exited with code 2.

### ISSUE THREAD

**Issue by ViperzSmurfz** [Seanghost117/GTA-V-Internal-Source#7]
Error code "MSB6006" gets thrown when building after adding the include <intrin.h>. Anyone know the cause?

**Comment by monkeycow123** [comment]
You're getting the error because a function is not returning a value.

**Comment by Tragic** [comment]
I also get this error.

**Comment by Tragic** [comment]
How did you manage to fix this OP?
